# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/138/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/138/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/justnik/CLionProjects/o-ran

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/justnik/CLionProjects/o-ran

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/138/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/138/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/justnik/CLionProjects/o-ran/CMakeFiles /home/justnik/CLionProjects/o-ran/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/justnik/CLionProjects/o-ran/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named o_ran

# Build rule for target.
o_ran: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 o_ran
.PHONY : o_ran

# fast build rule for target.
o_ran/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/o_ran.dir/build.make CMakeFiles/o_ran.dir/build
.PHONY : o_ran/fast

controller/Controller.o: controller/Controller.cpp.o

.PHONY : controller/Controller.o

# target to build an object file
controller/Controller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/o_ran.dir/build.make CMakeFiles/o_ran.dir/controller/Controller.cpp.o
.PHONY : controller/Controller.cpp.o

controller/Controller.i: controller/Controller.cpp.i

.PHONY : controller/Controller.i

# target to preprocess a source file
controller/Controller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/o_ran.dir/build.make CMakeFiles/o_ran.dir/controller/Controller.cpp.i
.PHONY : controller/Controller.cpp.i

controller/Controller.s: controller/Controller.cpp.s

.PHONY : controller/Controller.s

# target to generate assembly for a file
controller/Controller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/o_ran.dir/build.make CMakeFiles/o_ran.dir/controller/Controller.cpp.s
.PHONY : controller/Controller.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/o_ran.dir/build.make CMakeFiles/o_ran.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/o_ran.dir/build.make CMakeFiles/o_ran.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/o_ran.dir/build.make CMakeFiles/o_ran.dir/main.cpp.s
.PHONY : main.cpp.s

reader/JSONReader.o: reader/JSONReader.cpp.o

.PHONY : reader/JSONReader.o

# target to build an object file
reader/JSONReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/o_ran.dir/build.make CMakeFiles/o_ran.dir/reader/JSONReader.cpp.o
.PHONY : reader/JSONReader.cpp.o

reader/JSONReader.i: reader/JSONReader.cpp.i

.PHONY : reader/JSONReader.i

# target to preprocess a source file
reader/JSONReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/o_ran.dir/build.make CMakeFiles/o_ran.dir/reader/JSONReader.cpp.i
.PHONY : reader/JSONReader.cpp.i

reader/JSONReader.s: reader/JSONReader.cpp.s

.PHONY : reader/JSONReader.s

# target to generate assembly for a file
reader/JSONReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/o_ran.dir/build.make CMakeFiles/o_ran.dir/reader/JSONReader.cpp.s
.PHONY : reader/JSONReader.cpp.s

writer/ConsoleWriter.o: writer/ConsoleWriter.cpp.o

.PHONY : writer/ConsoleWriter.o

# target to build an object file
writer/ConsoleWriter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/o_ran.dir/build.make CMakeFiles/o_ran.dir/writer/ConsoleWriter.cpp.o
.PHONY : writer/ConsoleWriter.cpp.o

writer/ConsoleWriter.i: writer/ConsoleWriter.cpp.i

.PHONY : writer/ConsoleWriter.i

# target to preprocess a source file
writer/ConsoleWriter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/o_ran.dir/build.make CMakeFiles/o_ran.dir/writer/ConsoleWriter.cpp.i
.PHONY : writer/ConsoleWriter.cpp.i

writer/ConsoleWriter.s: writer/ConsoleWriter.cpp.s

.PHONY : writer/ConsoleWriter.s

# target to generate assembly for a file
writer/ConsoleWriter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/o_ran.dir/build.make CMakeFiles/o_ran.dir/writer/ConsoleWriter.cpp.s
.PHONY : writer/ConsoleWriter.cpp.s

writer/HTTPWriter.o: writer/HTTPWriter.cpp.o

.PHONY : writer/HTTPWriter.o

# target to build an object file
writer/HTTPWriter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/o_ran.dir/build.make CMakeFiles/o_ran.dir/writer/HTTPWriter.cpp.o
.PHONY : writer/HTTPWriter.cpp.o

writer/HTTPWriter.i: writer/HTTPWriter.cpp.i

.PHONY : writer/HTTPWriter.i

# target to preprocess a source file
writer/HTTPWriter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/o_ran.dir/build.make CMakeFiles/o_ran.dir/writer/HTTPWriter.cpp.i
.PHONY : writer/HTTPWriter.cpp.i

writer/HTTPWriter.s: writer/HTTPWriter.cpp.s

.PHONY : writer/HTTPWriter.s

# target to generate assembly for a file
writer/HTTPWriter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/o_ran.dir/build.make CMakeFiles/o_ran.dir/writer/HTTPWriter.cpp.s
.PHONY : writer/HTTPWriter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... o_ran"
	@echo "... controller/Controller.o"
	@echo "... controller/Controller.i"
	@echo "... controller/Controller.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... reader/JSONReader.o"
	@echo "... reader/JSONReader.i"
	@echo "... reader/JSONReader.s"
	@echo "... writer/ConsoleWriter.o"
	@echo "... writer/ConsoleWriter.i"
	@echo "... writer/ConsoleWriter.s"
	@echo "... writer/HTTPWriter.o"
	@echo "... writer/HTTPWriter.i"
	@echo "... writer/HTTPWriter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

